// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

import "@/app/global.css"
const { Children, Suspense } = require("react");


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "E-commerce Website",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import Header from "./components/header";

function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Suspense fallback={<h1>Loading the site!</h1>}>
          {children} {/* children must be inside Suspense */}
        </Suspense>
      </body>
    </html>
  );
}
export default Layout;
